### ISSUE TITLE
[Bug]: js-binary output will not exclude dev dependencies

### ISSUE THREAD

**Issue by zfy0701** [aspect-build/rules_js#1032] opened 2023-04-29 20:21 UTC
### What happened?

when build  js-binary target, I notice it will just put all the dependencies in the output tree, result a very big release binary

the code looks like this:
```
js_library(
    name = "image_lib",
    data = [":generate_dist"]
    deps = [
        ":node_modules",
        "//:node_modules/next",
        "//:node_modules/react",
        "//:node_modules/react-dom",
    ],
)

js_binary(
    name = "image_bin",
    chdir = "{}/dist".format(package_name()),
    copy_data_to_bin = True,
    data = [":image_lib"],
    entry_point = "dist/server.js"
)
```

is this intentional?
 otherwise I could make a sample project for you guys to debug

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
bazel 6.1.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
1.30.2

Language(s) and/or frameworks involved:
next.js

**Comment by jbedard** [comment] 2023-05-01 19:13
Just like non-bazel the `node_modules` directory contains everything when doing a local install. You need to specify each individual package if you want only a subset of them. Or you can use pnpm workspaces and create a project with only the dependencies you need for that `js_binary`.

**Comment by zfy0701** [comment] 2023-05-01 23:03
I see, but the arugment of add this feature is just like pnpm and others, when you install dependency you could have a flag to    only install dev dependencies.

another thing I tried is to have two npm_lock, on set with prod=true, and on set as dev=true, but unfortunately they will conflict and won't work

**Comment by jbedard** [comment] 2023-05-03 20:10
In your original example (the image_lib/bin) which dependencies are in the binary which you would not expect?

**Comment by zfy0701** [comment] 2023-05-03 23:07
add the following code to https://github.com/aspect-build/bazel-examples/blob/6445dd9f15d843232691cd4d5490814c8564ec86/next.js/apps/alpha/BUILD.bazel#L68

```
js_binary(
    name = "image_bin",
#    chdir = "{}/dist".format(package_name()),
    copy_data_to_bin = True,
    data = [
        ":node_modules",
        "//:node_modules/next",
        "//:node_modules/react",
        "//:node_modules/react-dom",
    ],
    entry_point = ":next.config.js"
)


js_image_layer(
    name = "layer",
    binary = ":image_bin",
    visibility = ["//visibility:public"],
)
```
and also it's import , then build
```bazel build apps/alpha:layer```

then open `bazel-bin/apps/alpha/layer_node_modules.tar.gz`, then
```ls -alh bazel-bin/apps/alpha/layer_node_modules.tar.gz```
it's 300M+, unzip and you will find it about 1G, if you use next to package standalone binary it will only give you about 100M+ uncompressed files

find the .aspectjs after unzip
you could find 
```
DX3906:.aspect_rules_js$ du -d 1 -h  | grep ext+swc-linu
 58M	./@next+swc-linux-arm-gnueabihf@13.0.5
 79M	./@next+swc-linux-x64-musl@13.0.5
 80M	./@next+swc-linux-x64-gnu@13.0.5
 72M	./@next+swc-linux-arm64-musl@13.0.5
 72M	./@next+swc-linux-arm64-gnu@13.0.5
```

```
DX3906:.aspect_rules_js$ du -d 1 -h  | grep @babel
552K	./@babel+generator@7.21.4
2.8M	./@babel+types@7.21.4
 40K	./@babel+code-frame@7.21.4
 48K	./@babel+helper-string-parser@7.19.4
720K	./@babel+traverse@7.21.4
108K	./@babel+compat-data@7.21.4
644K	./@babel+helpers@7.21.0
1.2M	./@babel+core@7.21.4
100K	./@babel+helper-compilation-targets@7.21.4_at_babel_core_7.21.4
112K	./@babel+template@7.20.7
 32K	./@babel+helper-simple-access@7.20.2
 40K	./@babel+helper-validator-option@7.21.0
180K	./@babel+helper-module-transforms@7.21.2
 88K	./@babel+helper-module-imports@7.21.4
 76K	./@babel+helper-validator-identifier@7.19.1
1.8M	./@babel+parser@7.21.4
 20K	./@babel+highlight@7.18.6
 20K	./@babel+helper-split-export-declaration@7.18.6
 40K	./@babel+helper-function-name@7.21.0
 20K	./@babel+helper-environment-visitor@7.18.9
 20K	./@babel+helper-hoist-variables@7.18.6
```

and many thing else that obviously should not be in final binary

**Comment by jbedard** [comment] 2023-05-15 23:01
Unfortunately I think this is correct. Nextjs declares dependencies on those swc packages and for some reason includes a lot of npm packages such as all those babel ones: https://unpkg.com/browse/next@13.4.2/dist/compiled/.

However it's probably the swc binaries that are adding all the size because rules_js doesn't filter optional deps based on platform, see https://docs.aspect.build/rules/aspect_rules_js/docs/npm_translate_lock#no_optional.

You could potentially use `no_optional` and declare a dependency on only the swc for the necessary platforms, especially if you only need swc in the image.

**Comment by alexeagle** [comment] 2023-08-08 22:39
Closing as it has been about 3 months since the last message, I assume "this is correct" from Jason means it's working as intended. Please comment again if that's wrong.

**Closed by alexeagle** 2023-08-08 22:39 UTC
Labels: bug, confirmation needed
