### ISSUE TITLE
[Bug]: Package `temp@0.4.0` fails to extract

### ISSUE THREAD

**Issue by Silic0nS0ldier** [aspect-build/rules_js#1840] opened 2024-07-05 01:32 UTC
### What happened?

The package `temp@0.4.0` cannot be extracted by the in-action extraction logic introduced in #1538 ([v1.40.0](https://github.com/aspect-build/rules_js/releases/tag/v1.40.0)).

**Command (`--sandbox_debug`)**
```
  (cd /Users/mele/.bazel/1ac9614be78e8b537b49f220ab76e96e/sandbox/darwin-sandbox/24/execroot/_main && \
  exec env - \
    TMPDIR=/tmp \
  /usr/bin/sandbox-exec -f /Users/mele/.bazel/1ac9614be78e8b537b49f220ab76e96e/sandbox/darwin-sandbox/24/sandbox.sb /Users/mele/.bazel/install/abee1bc4a5caa87f8299faf78a2e8b97/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/Users/mele/.bazel/1ac9614be78e8b537b49f220ab76e96e/sandbox/darwin-sandbox/24/stats.out' --graceful_sigterm external/bsd_tar_darwin_arm64/tar --extract --no-same-owner --no-same-permissions --strip-components 1 --file external/pnpm_deps__temp__0.4.0/package.tgz --directory bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/temp@0.4.0/node_modules/temp)
```

**Output**
```
gzip: (stdin): trailing garbage ignored
tar: Error opening archive: (null)
```

### Version

Development (host) and target OS/architectures:
```
❯ uname -a
Darwin Jordans-MBP 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

Output of `bazel --version`: `7.2.1`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: `1.42.3` (`WORKSPACE`)

Language(s) and/or frameworks involved: `pnpm-lock.yaml` version `6.0`, workspace enabled

**Comment by jbedard** [comment] 2024-12-16 23:42
Are you still seeing this issue? I'm looking into [a similar issue](https://github.com/aspect-build/rules_js/issues/2039) and can't reproduce this one atm.

**Comment by jbedard** [comment] 2024-12-16 23:52
Also can't reproduce it in rules_js v1.42.3 or bazel 7.2.1 so I'm going to close this for now, we can reopen it if you can still reproduce it.

**Closed by jbedard** 2024-12-16 23:52 UTC
Labels: bug
