### ISSUE TITLE
[Bug]: Patch changes not invalidating generated node_modules targets

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#600] opened 2022-11-09 15:00 UTC
### What happened?

I've noticed several times now that when adding and removing `patches` and `patch_args` entries from `npm_translate_lock`, a `bazel clean` is required to incorporate the changes.

### Version

Development (host) and target OS/architectures:

mac os, arm64

Output of `bazel --version`:

c07d97b61c35a08460cb7c2ebf7851bc68787ad7

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by kormide** [comment] 2022-11-25 20:25
@matthewjh I'm not able to reproduce this. Are you able to provide a repro?

**Comment by gregmagolan** [comment] 2022-12-02 20:43
Putting this on my list for next's weeks OSS bug squashing.

**Comment by gregmagolan** [comment] 2023-01-03 19:49
I did some digging and I don't see how did is going wrong. The patch files should be referenced by the npm_import for the package in question & that should trigger an invalidation when the patch files changes.

It is possible that the patch key was incorrect and the patch file was being silently ignored and not applied to the npm_import at all. I added a hard fail for this case since it is easy to hit: https://github.com/aspect-build/rules_js/commit/3bbb4c0ceba029a7c815e15bb3ed0bb5d461d33e.

Closing this as there I can't repro and from all my testing this is working as expected. @matthewjh please re-open if you think it is still valid.

**Closed by gregmagolan** 2023-01-03 19:49 UTC
Labels: bug, need: repro
