### ISSUE TITLE
[Bug]: Toolchain resolution broken when using bzlmod and js_image_layer

### ISSUE THREAD

**Issue by lqc** [aspect-build/rules_js#1316] opened 2023-10-16 09:01 UTC
### What happened?

I am able to successfully build a working image by adding ":tarball" target to ```e2e/js_image_oci```. 

I tried to do the same on a copy of ```e2e/js_image_oci```, but with WORKSPACE converted to bzlmod:

https://github.com/lqc/rules_js/commit/705f927dc63cff36e832524e01e5d52c2b9241a9

Whatever combination of "platform" and "toolchain" options I provide, I always end up with "js_image_layer" rule bundling the "darwin_amd64" Node.js instead of "linux_amd64". 

This might be related to #883, so it might be Bazel's fault.

Unless your OS/arch matches exactly your target, the only was to use rules_js right now seems to be without bzlmod entriely (trying to keep only JS rules in WORKSPACE.bzlmod) didn't work for me either.

### Version

Development (host) and target OS/architectures:

host: macOs 13.5.2 / Intel (amd64)
target: linux / amd64

Output of `bazel --version`:

aspect 5.7.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

See https://github.com/lqc/rules_js/commit/705f927dc63cff36e832524e01e5d52c2b9241a9

**Comment by jvliwanag** [comment] 2023-11-03 07:54
Adding a note that a partial bzlmod (excluding only rules_js) still worked for my minimal reproduction [here](https://github.com/jvliwanag/node-bazel-docker-repro/tree/not-bzlmod). In this sample, rules_oci was from bzlmod, while rules_js is defined in WORKSPACE.

Putting both on bzlmod didn't work though. See [here](https://github.com/jvliwanag/node-bazel-docker-repro/tree/main).

host: macos 14.0 / M2
target: linux / arm64

**Comment by gregmagolan** [comment] 2024-05-06 17:01
Closing as a duplicate of #1530

**Closed by gregmagolan** 2024-05-06 17:01 UTC
Labels: bug, untriaged
