### ISSUE TITLE
[Bug]: node module resolution fails after moving `package.json` to non-root package 

### ISSUE THREAD

**Issue by ztl8702** [aspect-build/rules_js#764] opened 2023-01-10 14:52 UTC
### What happened?

When moving a `package.json` from root package to a non-root package (and enabling pnpm workspaces), new, unexpected node module resolution issues occurred.

The nodejs binary that has node module resolution issue is from https://unpkg.com/browse/@tarojs/cli@3.5.11/

Here is how I invoked the problematic binary in Bazel:

https://github.com/zingzeu/bug-repro/blob/8c82debfded553ee782a3d17f0fe75150d655aab/app/BUILD.bazel#L36-L46

The problem (as described in "How to reproduce") did not exist with outside of Bazel.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `bazel 6.0.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

```
...
bazel_dep(name = "aspect_rules_js", version = "1.13.1")
bazel_dep(name = "aspect_bazel_lib", version = "1.18.0")

...
npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
...
```

[full file](https://github.com/zingzeu/bug-repro/blob/ec0f9e26f056c8250c959791629e866c8226c292/MODULE.bazel#L1)

Language(s) and/or frameworks involved: [Taro](https://docs.taro.zone/en/docs), which uses React, Babel and  Webpack under the hood. 

### How to reproduce

```shell
(I am not sure if this is a very minimal demo, but I try to make it reproducible)


1. git clone https://github.com/zingzeu/bug-repro && git checkout ec0f9e26f056c8250c959791629e866c8226c292
2. bazel build //app:miniapp

Expected: build succeeds

Actual: build fails with error: https://gist.github.com/ztl8702/b48e09003f1f5bfd2668cf91a4b55d31
```

### Any other information?

- At the same commit (https://github.com/zingzeu/bug-repro/commit/ec0f9e26f056c8250c959791629e866c8226c292), running the same binary outside (using this npm [script](https://github.com/zingzeu/bug-repro/blob/a95c37fa839b056302db58fb7c68b102dd1bc586/app/package.json#L3-L5)) of bazel works:
   ```
   git clone https://github.com/zingzeu/bug-repro && git checkout ec0f9e26f056c8250c959791629e866c8226c292
   cd app
   pnpm run build #works
   bazel build //app:miniapp # does not work
   ```
   
- At a previous commit, i.e. before switching to a sub-package, Bazel build also works.

   ```
   git clone https://github.com/zingzeu/bug-repro && git checkout 1798d6938c72767c93907fb96929c0286fcb1c58
   pnpm run build # works
   bazel build //app:miniapp # works
   ```

- So, the commit that causes build failure is https://github.com/zingzeu/bug-repro/commit/ec0f9e26f056c8250c959791629e866c8226c292

- Tried [hoisting](https://docs.aspect.build/rules/aspect_rules_js/docs/npm_import/#public_hoist_packages), didn't work: https://github.com/zingzeu/bug-repro/commit/a95c37fa839b056302db58fb7c68b102dd1bc586 (did I use hoisting correctly?)

### Fund our work

- [X] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/) #612015

**Comment by ztl8702** [comment] 2023-01-11 05:56
I am a Bazel newbie. So I would appreciate some debugging tips too. I do feel that the whole `bazel-*` tree is a blackbox to me.

**Comment by gregmagolan** [comment] 2023-01-13 07:00
The root cause here is undeclared dependencies in 3rd party npm packages. We have some docs on this here: https://docs.aspect.build/rules/aspect_rules_js/docs/pnpm#hoisting. In most cases, the same issue can be reproduced outside of Bazel with pnpm when `hoist=false` is set in `.npmrc`.

I quickly got through two failures by creating a root package.json that uses pnpm packageExtensions to inject the missing deps:
```
{
  "private": true,
  "pnpm": {
    "packageExtensions": {
      "@tarojs/helper": {
        "dependencies": {
            "@babel/traverse": "*"
        }
      },
      "loader-runner": {
        "dependencies": {
          "@tarojs/taro-loader": "*"
        }
      }
    }
  }
}
```

however, there is a strange resolution failure in taro-ui where it can't find `@tarojs/components` even if that dep is injected with
```
"taro-ui": {
  "dependencies": {
      "@tarojs/components": "*"
  }
},
```
Failure looks like this:
```
$ bazel build //app:miniapp
WARNING: For repository 'aspect_bazel_lib', the root module requires module version aspect_bazel_lib@1.18.0, but got aspect_bazel_lib@1.19.0 in the resolved dependency graph.
INFO: Analyzed target //app:miniapp (1783 packages loaded, 13043 targets configured).
INFO: Found 1 target...
ERROR: /Users/greg/aspect/tmp/bug-repro/app/BUILD.bazel:39:14: Taro app/dist failed: (Exit 1): miniapp__js_binary.sh failed: error executing command (from target //app:miniapp) bazel-out/darwin-opt-exec-2B5CBBC6/bin/app/miniapp__js_binary.sh build --type weapp

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
- 即将开始启动编译，请稍等~
🙅   编译失败. 1/12/2023, 10:58:31 PM

👽 Taro v3.5.11


编译  发现入口  src/app.tsx
编译  发现页面  src/pages/index/index.tsx
../node_modules/.aspect_rules_js/taro-ui@3.1.0-beta.4_3ajq4bbqzvs625arex6eu5nw7e/node_modules/taro-ui/dist/index.esm.js
Module not found: Can't resolve '@tarojs/components' in '/private/var/tmp/_bazel_greg/053f956009fdc91b989218ecdd56cf0b/sandbox/darwin-sandbox/2838/execroot/_main/bazel-out/darwin-fastbuild/bin/node_modules/.aspect_rules_js/taro-ui@3.1.0-beta.4_3ajq4bbqzvs625arex6eu5nw7e/node_modules/taro-ui/dist'

Target //app:miniapp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 23.839s, Critical Path: 16.71s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

I'm not familiar with taro-ui at but with a bit of digging you should be able to get past this failure.

In any case, this is not a rules_js bug so closing this issue. Community slack support on the Bazel slack #javascript channel is probably the best place to seek help if you get stuck.

**Closed by gregmagolan** 2023-01-13 07:00 UTC
Labels: bug

**Comment by ztl8702** [comment] 2023-01-15 06:14
adding "@tarojs/plugin-platform-weapp" to "taro-ui"'s deps seemed to do the trick

```
"packageExtensions": {
      "@tarojs/helper": {
        "dependencies": {
          "@babel/traverse": "*"
        }
      },
      "webpack": {
        "dependencies": {
          "@tarojs/taro-loader": "*"
        }
      },
      "loader-runner": {
        "dependencies": {
          "@tarojs/taro-loader": "*"
        }
      },
      "taro-ui": {
        "dependencies": {
          "@tarojs/plugin-platform-weapp":"*"
        }
      }
    }
```
