### ISSUE TITLE
No code coverage when testing with jest

### ISSUE THREAD

**Issue by GV94** [aspect-build/rules_js#153] opened 2022-06-03 13:28 UTC
I am trying to add code coverage reports to opened PRs in my projects CI pipelines (using rules_js), but I am just getting empty reports.

I stumbled across [this example](https://github.com/subnova/coverage_test), which is working for me. However, it is using the old ts_project rule from bazel. I forked and ported it to use rules_js (as that is what I am using), and the resulting setup is again getting empty code coverage reports. Is this a problem with rules_js, am I doing something wrong, or is it something else entirely?

Here is a version where code coverage is working (using old ts_project from bazel): https://github.com/GV94/bazel_jest_test_coverage.
Here is the same code ported to use rules_js (empty code coverage reports): https://github.com/GV94/bazel_jest_test_coverage/pull/1.

**Comment by bazaglia** [comment] 2022-06-03 17:48
I also can't find a way to get code coverage even though it used to work in `rules_nodejs`. This can be verified by running the minimal example in [aspect-build/rules_jest](https://github.com/aspect-build/rules_jest/) adding the attribute `collectCoverage: true` to the jest.config.js file.

Also tried on the just-released version 0.10.0 and confirm it's not working either.

<img width="826" alt="Screenshot 2022-06-03 at 19 46 59" src="https://user-images.githubusercontent.com/6966980/171918640-80330405-ef56-43ee-948f-9ab94fe1b852.png">

**Comment by bazaglia** [comment] 2022-06-03 17:52
@alexeagle Maybe you have an idea of what's causing this?

**Comment by alexeagle** [comment] 2022-06-03 21:16
Yes, coverage under Bazel is a complex beast and only works in certain conditions that have been carefully curated. So it's not surprising this feature is missing.

@toxicable has been our JS-bazel expert on this in the past and may have some suggestions.

Though if you're just passing a flag to Jest, I'd expect Jest itself to have the behavior they indicate under that flag, regardless of whether `bazel coverage` does anything correct before or after the test process spawn to understand the side-effects.

**Comment by alexeagle** [comment] 2022-06-03 21:50
Looks like a bug in Jest :(
https://github.com/alexeagle/jest-coverage-repro

I'm guessing the fix for jest-haste-map for `enableSymlinks` is not fixed at the right layer, so their coverage collection (maybe using some other library) doesn't respect it.

**Comment by bazaglia** [comment] 2022-06-04 00:40
Thanks for sharing! I understand there is a bug in Jest and you reproduced it only by using symlinks. I found a merged PR where aparently this was discussed in first place and see you in that discussion too: https://github.com/facebook/jest/pull/9351

Just a question – how come Jest coverage reports work in rules_nodejs? The problem only happens on rules_js. I'm still trying to get a workaround given the limitation, but it would help if I can get a clue on why it works on rules_nodejs.

**Comment by alexeagle** [comment] 2022-06-04 00:41
That's because the working directory in rules_js is in the bazel-out/arch/bin folder

**Comment by gregmagolan** [comment] 2022-06-04 14:40
In rules_nodejs, it is an explicit feature in the nodejs_binary launcher https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/launcher.sh#L463. It runs an lcov merger script after the node process exits and outputs the coverage data to the location & format that bazel expects.

We can add the same feature to the js_binary launcher as well.

**Comment by gregmagolan** [comment] 2022-06-04 14:41
I'll put that on the list for after I finish up the symlink guards so that processes don't escape the sandbox. Someone else could pick it up as well as it is a fairly self-contained feature.

**Comment by GV94** [comment] 2022-06-07 09:13
> In rules_nodejs, it is an explicit feature in the nodejs_binary launcher https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/node/launcher.sh#L463. It runs an lcov merger script after the node process exits and outputs the coverage data to the location & format that bazel expects.
> 
> We can add the same feature to the js_binary launcher as well.

Would that fix this issue that I am having?

**Comment by alexeagle** [comment] 2022-06-07 14:22
I think you'd also need Jest to fix that bug in this thread, it doesn't produce any coverage data when run in bazel-out.

**Comment by GV94** [comment] 2022-06-10 09:59
The problem seems to be jest setting the rootdir to where the `jest.config.js`  during execution. When run through bazel this will be the directory where the symlink is to `jest.config.js`. When deciding what files to check for coverage collection, it will only consider files that are under the rootdir (it filters the rest away).

During test execution when node imports modules, it will not preserve the symlinks, it will dereference them. It is these dereferenced filepaths that end up in the coverage sources collected by jest. The result is that there is a mismatch between what files jest considers for testing (must be under rootdir), the source files for which coverage is collected.

**Comment by GV94** [comment] 2022-06-13 07:35
Potentially. Theoretically is true to me, but I haven't tried it in practice. We made a quick test where we explicitly set it to the folder where our source code is. This had other implications that made some tests fail (like requiring internal packages created with bazel), but when disabling those tests test coverage worked fine. If you can reliably (across different OS:s/machines) set it to the folder to which the sandbox symlinks points to, it might work fine.

**Comment by alexeagle** [comment] 2022-06-14 23:23
@bazaglia confirms that now that #114 is fixed, jest can produce the coverage data. It's just a matter of plumbing that through to where Bazel expects now.

**Comment by GV94** [comment] 2022-06-15 05:29
Yes, we've removed the patch we made for jest and it is working as expected. Thanks!

**Comment by bazaglia** [comment] 2022-06-15 06:13
@GV94  there is still no support for integration with Bazel coverage by the rules even though many issues were solved by the PR mentions above. Maybe good to leave this issue open so this can be tracked?

**Closed** 2022-06-28 01:28 UTC
