### ISSUE TITLE
[Bug]: Runfiles in Docker Image not working

### ISSUE THREAD

**Issue by supercairos** [aspect-build/rules_js#612] opened 2022-11-15 15:20 UTC
### What happened?

While using a `js_rules` inside the `js_image_helper`, some environement variable seems to be missing since 1.6.X

In 1.6.X:
```
{
  OLDPWD: '/',
  JS_BINARY__LOG_ERROR: '1',
  FEDERATION_FILE: '/config/federation.json',
  JS_BINARY__FS_PATCH_ROOTS: '/:/app/hydra-ui/img-bin.sh.runfiles',
  PATH: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/hydra-ui/img-bin_node_bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  JS_BINARY__COMPILATION_MODE: 'fastbuild',
  JS_BINARY__COPY_DATA_TO_BIN: '1',
  JS_BINARY__PACKAGE: 'hydra-ui',
  JS_BINARY__NODE_WRAPPER: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/hydra-ui/img-bin_node_bin/node',
  JS_BINARY__TARGET_NAME: 'img-bin',
  SHLVL: '0',
  JS_BINARY__TARGET: '//hydra-ui:img-bin',
  JS_BINARY__RUNFILES: '/app/hydra-ui/img-bin.sh.runfiles',
  JS_BINARY__EXECROOT: '/',
  NODE_CONFIG_DIR: '/config',
  BAZEL_BINDIR: '.',
  JS_BINARY__LOG_PREFIX: 'aspect_rules_js[js_binary]',
  HOME: '/var/www',
  JS_BINARY__NODE_PATCHES: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/../aspect_rules_js/js/private/node-patches/register.js',
  JS_BINARY__LOG_FATAL: '1',
  JS_BINARY__TARGET_CPU: 'darwin_arm64',
  PWD: '/',
  JS_BINARY__WORKSPACE: 'com_shadow_cbp',
  JS_BINARY__BINDIR: 'bazel-out/darwin_arm64-fastbuild-ST-4a519fd6d3e4/bin',
  JS_BINARY__NODE_BINARY: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/../nodejs_linux_amd64/bin/nodejs/bin/node',
  JS_BINARY__BUILD_FILE_PATH: 'hydra-ui/BUILD',
  HOSTNAME: 'b02760d0422c',
  RUNFILES: '/app/hydra-ui/img-bin.sh.runfiles',
  JS_BINARY__PATCH_NODE_FS: '1',
  JS_BINARY__NODE_PATCHES_DEPTH: '.'
}
```

In 1.5.3
```
{
  'BASH_FUNC_runfiles_export_envvars%%': '() {  if [[ ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" && ! -d "${RUNFILES_DIR:-/dev/null}" ]]; then\n' +
    ' return 1;\n' +
    ' fi;\n' +
    ' if [[ ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then\n' +
    ' if [[ -f "$RUNFILES_DIR/MANIFEST" ]]; then\n' +
    ' export RUNFILES_MANIFEST_FILE="$RUNFILES_DIR/MANIFEST";\n' +
    ' else\n' +
    ' if [[ -f "${RUNFILES_DIR}_manifest" ]]; then\n' +
    ' export RUNFILES_MANIFEST_FILE="${RUNFILES_DIR}_manifest";\n' +
    ' else\n' +
    ' export RUNFILES_MANIFEST_FILE=;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' else\n' +
    ' if [[ ! -d "${RUNFILES_DIR:-/dev/null}" ]]; then\n' +
    ' if [[ "$RUNFILES_MANIFEST_FILE" == */MANIFEST && -d "${RUNFILES_MANIFEST_FILE%/MANIFEST}" ]]; then\n' +
    ' export RUNFILES_DIR="${RUNFILES_MANIFEST_FILE%/MANIFEST}";\n' +
    ' export JAVA_RUNFILES="$RUNFILES_DIR";\n' +
    ' else\n' +
    ' if [[ "$RUNFILES_MANIFEST_FILE" == *_manifest && -d "${RUNFILES_MANIFEST_FILE%_manifest}" ]]; then\n' +
    ' export RUNFILES_DIR="${RUNFILES_MANIFEST_FILE%_manifest}";\n' +
    ' export JAVA_RUNFILES="$RUNFILES_DIR";\n' +
    ' else\n' +
    ' export RUNFILES_DIR=;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' fi\n' +
    '}',
  'BASH_FUNC_rlocation%%': '() {  if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): start" 1>&2;\n' +
    ' fi;\n' +
    ' if [[ "$1" =~ $_RLOCATION_ISABS_PATTERN ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): absolute path, return" 1>&2;\n' +
    ' fi;\n' +
    ' echo "$1";\n' +
    ' else\n' +
    ' if [[ "$1" == ../* || "$1" == */.. || "$1" == ./* || "$1" == */./* || "$1" == "*/." || "$1" == *//* ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "ERROR[runfiles.bash]: rlocation($1): path is not normalized" 1>&2;\n' +
    ' fi;\n' +
    ' return 1;\n' +
    ' else\n' +
    ' if [[ "$1" == \\\\* ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "ERROR[runfiles.bash]: rlocation($1): absolute path without" "drive name" 1>&2;\n' +
    ' fi;\n' +
    ' return 1;\n' +
    ' else\n' +
    ' if [[ -e "${RUNFILES_DIR:-/dev/null}/$1" ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): found under RUNFILES_DIR ($RUNFILES_DIR), return" 1>&2;\n' +
    ' fi;\n' +
    ' echo "${RUNFILES_DIR}/$1";\n' +
    ' else\n' +
    ' if [[ -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): looking in RUNFILES_MANIFEST_FILE ($RUNFILES_MANIFEST_FILE)" 1>&2;\n' +
    ' fi;\n' +
    ' local -r result=$(grep -m1 "^$1 " "${RUNFILES_MANIFEST_FILE}" | cut -d \' \' -f 2-);\n' +
    ' if [[ -z "$result" ]]; then\n' +
    ' local prefix="$1";\n' +
    ' local prefix_result=;\n' +
    ' local new_prefix=;\n' +
    ' while true; do\n' +
    ' new_prefix="${prefix%/*}";\n' +
    ' [[ "$new_prefix" == "$prefix" ]] && break;\n' +
    ' prefix="$new_prefix";\n' +
    ' prefix_result=$(grep -m1 "^$prefix " "${RUNFILES_MANIFEST_FILE}" | cut -d \' \' -f 2-);\n' +
    ' [[ -z "$prefix_result" ]] && continue;\n' +
    ' local -r candidate="${prefix_result}${1#"${prefix}"}";\n' +
    ' if [[ -e "$candidate" ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): found in manifest as ($candidate) via prefix ($prefix)" 1>&2;\n' +
    ' fi;\n' +
    ' echo "$candidate";\n' +
    ' return 0;\n' +
    ' fi;\n' +
    ' break;\n' +
    ' done;\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): not found in manifest" 1>&2;\n' +
    ' fi;\n' +
    ' echo "";\n' +
    ' else\n' +
    ' if [[ -e "$result" ]]; then\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "INFO[runfiles.bash]: rlocation($1): found in manifest as ($result)" 1>&2;\n' +
    ' fi;\n' +
    ' echo "$result";\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' else\n' +
    ' if [[ "${RUNFILES_LIB_DEBUG:-}" == 1 ]]; then\n' +
    ' echo "ERROR[runfiles.bash]: cannot look up runfile \\"$1\\" " "(RUNFILES_DIR=\\"${RUNFILES_DIR:-}\\"," "RUNFILES_MANIFEST_FILE=\\"${RUNFILES_MANIFEST_FILE:-}\\")" 1>&2;\n' +
    ' fi;\n' +
    ' return 1;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' fi;\n' +
    ' fi\n' +
    '}',
  OLDPWD: '/',
  JS_BINARY__LOG_ERROR: '1',
  FEDERATION_FILE: '/config/federation.json',
  JS_BINARY__FS_PATCH_ROOTS: '/:/app/hydra-ui/img-bin.sh.runfiles',
  PATH: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/hydra-ui/img-bin_node_bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  JS_BINARY__COMPILATION_MODE: 'fastbuild',
  JS_BINARY__NODE_WRAPPER: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/hydra-ui/img-bin_node_bin/node',
  _RLOCATION_ISABS_PATTERN: '^/[^/].*',
  SHLVL: '0',
  JS_BINARY__TARGET: '//hydra-ui:img-bin',
  NODE_CONFIG_DIR: '/config',
  BAZEL_BINDIR: '.',
  JS_BINARY__LOG_PREFIX: 'aspect_rules_js[js_binary]',
  HOME: '/var/www',
  JS_BINARY__NODE_PATCHES: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/../aspect_rules_js/js/private/node-patches/register.js',
  JS_BINARY__LOG_FATAL: '1',
  JS_BINARY__TARGET_CPU: 'darwin_arm64',
  PWD: '/',
  JS_BINARY__WORKSPACE: 'com_shadow_cbp',
  RUNFILES_DIR: '/app/hydra-ui/img-bin.sh.runfiles',
  JS_BINARY__BINDIR: 'bazel-out/darwin_arm64-fastbuild-ST-4a519fd6d3e4/bin',
  JS_BINARY__NODE_BINARY: '/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/../nodejs_linux_amd64/bin/nodejs/bin/node',
  JS_BINARY__BUILD_FILE_PATH: 'hydra-ui/BUILD',
  HOSTNAME: 'e795a74203ce',
  RUNFILES: '/app/hydra-ui/img-bin.sh.runfiles',
  JS_BINARY__PATCH_NODE_FS: '1',
  JS_BINARY__NODE_PATCHES_DEPTH: '.'
}
```

Running the Runfile library in 1.6.X version trigger this error:
```
/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/node_modules/.aspect_rules_js/@bazel+runfiles@5.7.1/node_modules/@bazel/runfiles/runfiles.js:26
            throw new Error('Every node program run under Bazel must have a $RUNFILES_DIR or $RUNFILES_MANIFEST_FILE environment variable');
            ^

Error: Every node program run under Bazel must have a $RUNFILES_DIR or $RUNFILES_MANIFEST_FILE environment variable
    at new Runfiles (/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/node_modules/.aspect_rules_js/@bazel+runfiles@5.7.1/node_modules/@bazel/runfiles/runfiles.js:26:19)
    at Object.<anonymous> (/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/node_modules/.aspect_rules_js/@bazel+runfiles@5.7.1/node_modules/@bazel/runfiles/index.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/hydra-ui/img-bin.sh.runfiles/com_shadow_cbp/node_modules/.aspect_rules_js/@shadow+utils@0.0.0/node_modules/@shadow/utils/src/utils.js:24:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
 ```

### Version

Bazel 5.3.2
rules_js 1.6.X

### How to reproduce

```shell
Use the runfile in the E2E js_image project
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment] 2022-11-15 20:03
This looks like a dup of https://github.com/aspect-build/rules_js/issues/553 as `node_modules/.aspect_rules_js/@bazel+runfiles@5.7.1` is in the callstack

**Comment by gregmagolan** [comment] 2022-11-23 22:15
The fix for this landed in rules_nodejs: https://github.com/bazelbuild/rules_nodejs/commit/11395ea1bd86f5a3d62c1d7eaab7c1af3d0896f2

Will be available in the next release of `@bazel/runfiles`

**Comment by gregmagolan** [comment] 2022-11-30 03:30
`@bazel/runfiles` 5.7.2 is out with the fix https://www.npmjs.com/package/@bazel/runfiles

**Comment by gregmagolan** [comment] 2022-11-30 03:30
@supercairos Can you please update to that version and confirm it solves your problem?

**Comment by gregmagolan** [comment] 2023-01-25 19:43
@devversion Confirmed this fixes the issue.

**Closed by gregmagolan** 2023-01-25 19:43 UTC
Labels: bug
