### ISSUE TITLE
[Bug]: js_image_layer is broken with bzlmod

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/rules_js#1530] opened 2024-03-19 18:35 UTC
### What happened?

Currently, cross compiling js_image_layer through `platform` attribute is broken due to this line [here](https://github.com/bazelbuild/rules_nodejs/blob/943800d8d601872dae53f5c1e17414d316834cac/MODULE.bazel#L19)  where linux toolchains are not registered first like it is in the WORKSPACE version. 

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
When building the image from Darwin to Linux, the following BUILD will produce an image that contains nodejs interpreter for darwin instead of linux.


js_binary(
  name = ":binary"
)

platform(
  name = "linux_amd64",
  constraint_values = [
      "@platforms//os:linux",
      "@platforms//cpu:x86_64",
  ],
)

js_image_layer(
  name = name,
  binary = ":binary",
  platform = ":linux_amd64"
)
```

**Comment by markuskobler** [comment] 2024-04-22 20:27
Is there a simple work around for this issue other than using `WORKSPACE`?

**Comment by thesayyn** [comment] 2024-04-22 21:55
You can use `--extra_toolchains` command line flag to register linux toolchains first. That should work.

**Comment by thesayyn** [comment] 2024-04-22 21:56
@jbedard @gregmagolan we should make this change in rules_nodejs and include in rules_js 2.0

**Comment by gregmagolan** [comment] 2024-05-06 15:57
> @jbedard @gregmagolan we should make this change in rules_nodejs and include in rules_js 2.0

Yes, we should fix this. Possibly fix the cc toolchain coupling in the rules_nodejs provider as well.

**Comment by gregmagolan** [comment] 2024-05-06 16:53
Duplicate of https://github.com/aspect-build/rules_js/issues/1316

**Comment by gregmagolan** [comment] 2024-05-06 22:28
Updated e2e/js_image_oci to build with bzlmod here https://github.com/aspect-build/rules_js/pull/1704. That stands-in as a repro for this issue now.

**Closed** 2024-06-06 18:47 UTC
Labels: bug

**Comment by gregmagolan** [comment] 2024-06-06 19:47
Landed on main. Fix will be included in the next rules_js 2 RC (current latest is rc4)
