### ISSUE TITLE
[Bug]: Running Nextjs example in Docker fails with `/app/apps/alpha/bin.runfiles/__main__/apps/alpha/bin.sh: line 379: cd: apps/alpha/dist: No such file or directory`

### ISSUE THREAD

**Issue by noelenwenede** [aspect-build/rules_js#921] opened 2023-03-03 10:51 UTC
### What happened?

I have been working on setting up the [nextjs example](https://github.com/aspect-build/bazel-examples/tree/main/next.js) in this repository to work on docker. 

I have combined the image example [js_image](https://github.com/aspect-build/rules_js/tree/main/e2e/js_image_oci) with the [nextjs docker example implementation](https://github.com/vercel/next.js/tree/canary/examples/with-docker) to successfully create a docker image.

I get the error below when I try to run the docker image:

```
/app/apps/alpha/bin.runfiles/__main__/apps/alpha/bin.sh: line 379: cd: apps/alpha/dist: No such file or directory
```

I have a fork of the repository with the changes required to build the image [here](https://github.com/noelenwenede/bazel-examples/tree/main/next.js).

Side Note:
Inspecting the directories in the generated image `apps/alpha/dist` directory exist inside  the`/app/apps/alpha/bin.runfiles/__main__` (I believe the issue may be related to `BAZEL_BINDIR`).  

Running the docker image in https://github.com/aspect-build/rules_js/tree/main/e2e/js_image_oci here works fine. So I'm unsure where the error comes from.

### Version

Development (host) and target OS/architectures: MacBook Pro Monterey (M1)

Output of `bazel --version`: bazel 6.0.0-homebrew

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
1. rules_js-1.20.1
2. rules_ts-1.3.1
3. rules_python-0.14.0
4. rules_pkg-0.8.0
5. rules_oci-0.3.1

Language(s) and/or frameworks involved:
1. next.js
2. typescript

### How to reproduce

```shell
1. Clone https://github.com/noelenwenede/bazel-examples/tree/main/next.js
2.  cd next.js
3. bazel build //apps/alpha:next_tarball
4. docker load --input $(bazel cquery --output=files //apps/alpha:next_tarball)
5. docker run -p 3000:3000 -t -i nextjs/js:latest
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by noelenwenede** [comment] 2023-03-07 10:06
I found a solution to this problem but I'm not certain if it is how `rules_js` and `rules_oci` intends for it to work considering the examples worked straight out the box without needing same configuration.

First I added `workdir` field to the `oci_image` rule:
```starlark
oci_image(
        name = "image",
        cmd = ["/app/examples/nextjs/bin"],
        entrypoint = ["bash"],
        tars = [":transitioned_layers"],
        base = "@debian_amd64//:image",
        architecture = select({
            "@platforms//cpu:arm64": "arm64",
            "@platforms//cpu:x86_64": "amd64",
        }),
        workdir = "/app/{}/bin.runfiles/onefleet".format(native.package_name()), # <-------
    )
```

Then I added all required `npm dependencies` to the `js_binary` rule:

```starlark
npm_deps = ["//:node_modules/next", ...]
js_binary(
        name = "bin",
        chdir = "{}/dist".format(native.package_name()),
        copy_data_to_bin = False,
        data = [":generate_dist"] + npm_deps, # <------
        entry_point = "dist/server.js",
    )
```

This works fine with nextjs `standalone` build. It should work fine for `none standalone` builds following the same pattern.

I just need a confirmation on the alignment of this approach with how these rules are intended to work.

**Comment by gregmagolan** [comment] 2023-03-11 00:06
Thanks for the detailed report. @thesayyn is the export on the js_image_layer rule and best to comment on this.

**Comment by jamesthompson** [comment] 2023-03-27 18:55
@noelenwenede do you have your fix published somewhere locally? I'm blocked by this issue at the moment trying to containerize my next.js application..._

**Comment by noelenwenede** [comment] 2023-03-28 08:41
> @noelenwenede do you have your fix published somewhere? I'm blocked by this issue at the moment trying to containerize my next.js application..._

Hi @jamesthompson, yes I found a fix. If you're using a `standalone` next build then you just need to copy the standalone directory a to binary and build the image layers using this binary. Then when using the OCI image rule, you need to set the working directory.

The build file in this [fork](https://github.com/noelenwenede/bazel-examples/blob/main/next.js/bazel/next.bzl) shows an example implementation.

NB: If your Workspace is named, then you need to replace` __main__` with the name of your workspace in the snippet below

```starlark
oci_image(
        name = "{}_image".format(name),
        cmd = ["/app/apps/alpha/bin"],
        entrypoint = ["bash"],
        tars = [":transitioned_layers"],
        base = "@debian_amd64//:image",
        architecture = select({
            "@platforms//cpu:arm64": "arm64",
            "@platforms//cpu:x86_64": "amd64",
        }),
        workdir = "/app/{}/bin.runfiles/__main__".format(native.package_name()), # <--- __main__ or [workspace_name]
    )
```

**Comment by jamesthompson** [comment] 2023-03-28 11:34
@noelenwenede I'm still getting the same js_image_layer errors. Many thanks nevertheless for your help!

Unfortunately, being able to containerize our next application is a deal breaker for us with rules_js, so we're flat out stuck. I think we're going to have to abandon rules_js for the foreseeable future. Being able to just build shared proto code between the backend and frontend seems like such an impossible yet necessary dream for web development.

**Comment by thesayyn** [comment] 2023-03-28 11:56
the principled fix for this is to set `workdir` as @noelenwenede suggested. js_image_layer is only responsible for laying out tar files that mimic the runfiles layout that bazel lays.

**Comment by jamesthompson** [comment] 2023-03-28 12:11
@thesayyn I couldn't reproduce the fix in my attempts with the workdir setting

**Comment by thesayyn** [comment] 2023-03-28 12:36
it seems to work with these patches; i am not sure why it didn't work before but upgrading the rules_oci version seem to fix it. 

```diff
diff --git a/next.js/WORKSPACE.bazel b/next.js/WORKSPACE.bazel
index 08be84d..7cd5675 100644
--- a/next.js/WORKSPACE.bazel
+++ b/next.js/WORKSPACE.bazel
@@ -89,10 +89,10 @@ rules_pkg_dependencies()
 
 # Rules OCI
 http_archive(
-    name = "contrib_rules_oci",
-    sha256 = "929da1362e27dc38206a116783d2b3efb95bcb165bdbc62a8190013e612a9b51",
-    strip_prefix = "rules_oci-0.3.1",
-    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v0.3.1/rules_oci-v0.3.1.tar.gz",
+    name = "rules_oci",
+    sha256 = "4a738bdbeacb0e1df070209dddfa7b55fed9bbc553b905cf3d2dd25115e0b598",
+    strip_prefix = "rules_oci-0.3.8",
+    url = "https://github.com/bazel-contrib/rules_oci/releases/download/v0.3.8/rules_oci-v0.3.8.tar.gz",
 )
 
 # Fetches the rules_oci dependencies.
@@ -100,23 +100,27 @@ http_archive(
 # you should fetch it *before* calling this.
 # Alternatively, you can skip calling this function, so long as you've
 # already fetched all the dependencies.
-load("@contrib_rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")
+load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")
 
 rules_oci_dependencies()
 
-load("@contrib_rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "LATEST_ZOT_VERSION", "oci_register_toolchains")
+load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "oci_register_toolchains")
 
 oci_register_toolchains(
     name = "oci",
-    crane_version = LATEST_CRANE_VERSION,
-    zot_version = LATEST_ZOT_VERSION,
+    crane_version = LATEST_CRANE_VERSION
 )
 
-## Pull base images
-load(":pull.bzl", "oci_pull")
+load("@rules_oci//oci:pull.bzl", "oci_pull")
+
 
 oci_pull(
-    name = "debian_amd64",
-    architecture = "amd64",
-    image = "thesayyn/debian:oci",
+    name = "debian",
+    # latest tag as of 28 March 2023
+    digest = "sha256:7b991788987ad860810df60927e1adbaf8e156520177bd4db82409f81dd3b721",
+    image = "index.docker.io/library/debian",
+    platforms = [
+        "linux/amd64",
+        "linux/arm64"
+    ],
 )
diff --git a/next.js/apps/alpha/generate_dist.sh b/next.js/apps/alpha/generate_dist.sh
old mode 100644
new mode 100755
diff --git a/next.js/bazel/next.bzl b/next.js/bazel/next.bzl
index 2b5edc7..8e3e35f 100644
--- a/next.js/bazel/next.bzl
+++ b/next.js/bazel/next.bzl
@@ -1,7 +1,7 @@
 load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_image_layer", "js_run_binary", "js_run_devserver")
 load("@aspect_bazel_lib//lib:run_binary.bzl", "run_binary")
-load("@contrib_rules_oci//oci:defs.bzl", "oci_image")
-load("@contrib_rules_oci//oci/private:tarball.bzl", "oci_tarball")
+load("@rules_oci//oci:defs.bzl", "oci_image")
+load("@rules_oci//oci/private:tarball.bzl", "oci_tarball")
 load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
 
 def next(
@@ -261,8 +261,8 @@ def next(
         name = "layers",
         binary = ":bin",
         platform = select({
-            "@platforms//cpu:arm64": "linux_arm64",
-            "@platforms//cpu:x86_64": "linux_amd64",
+            "@platforms//cpu:arm64": ":arm64_linux",
+            "@platforms//cpu:x86_64": ":amd64_linux",
         }),
         root = "/app",
     )
@@ -271,8 +271,8 @@ def next(
         name = "transitioned_layers",
         srcs = [":layers"],
         target_platform = select({
-            "@platforms//cpu:arm64": "linux_arm64",
-            "@platforms//cpu:x86_64": "linux_amd64",
+            "@platforms//cpu:arm64": ":arm64_linux",
+            "@platforms//cpu:x86_64": ":amd64_linux",
         }),
     )
 
@@ -281,7 +281,10 @@ def next(
         cmd = ["/app/apps/alpha/bin"],
         entrypoint = ["bash"],
         tars = [":transitioned_layers"],
-        base = "@debian_amd64//:image",
+        base = select({
+            "@platforms//cpu:arm64": "@debian_linux_arm64",
+            "@platforms//cpu:x86_64": "@debian_linux_amd64",
+        }),
         architecture = select({
             "@platforms//cpu:arm64": "arm64",
             "@platforms//cpu:x86_64": "amd64",
diff --git a/next.js/pull.bzl b/next.js/pull.bzl
deleted file mode 100644
index 79aa4d6..0000000
--- a/next.js/pull.bzl
+++ /dev/null
@@ -1,34 +0,0 @@
-"""A repository rule fetching container images using crane.
-
-This ought to come with rules_oci, see
-https://github.com/bazel-contrib/rules_oci/issues/63
-"""
-_PULL_TMPL = """\
-# based on https://github.com/bazel-contrib/rules_oci/blob/b900a6322ae4e68b431f7d65ebfef604657bd030/example/BUILD.bazel#L19-L43
-genrule(
-    name = "image",
-    outs = ["layout"],
-    cmd = "$(CRANE_BIN) pull {image} $@ --format=oci --platform=linux/{architecture}",
-    message = "Pulling {image} for linux/{architecture}",
-    output_to_bindir = True,
-    local = True, # needs to run locally to able to use credential helpers
-    toolchains = [
-        "@oci_crane_toolchains//:current_toolchain",
-    ],
-    visibility = ["//visibility:public"],
-)
-"""
-
-def _pull_impl(rctx):
-    rctx.file("BUILD.bazel", _PULL_TMPL.format(
-        architecture = rctx.attr.architecture,
-        image = rctx.attr.image,
-    ))
-
-oci_pull = repository_rule(
-    implementation = _pull_impl,
-    attrs = {
-        "image": attr.string(mandatory = True),
-        "architecture": attr.string(mandatory = True),
-    },
-)

```

**Comment by jamesthompson** [comment] 2023-03-28 12:42
I just managed to get it to build as well, the generate_dist.sh script wasn't copying the server.js file properly rather it was copying a symlink to the file. I fixed that with swapping out `cp -rf` for `cp "$NEXT_DIR/standalone/server.js" "$DIST_DIR/"`. Just managed to build it thank goodness.

**Comment by LavaToaster** [comment] 2023-04-12 15:16
:wave: Hello

@thesayyn I'm not sure how this is a just documentation issue. It feels to me that it should be correct and valid that the entrypoint we're providing to `oci_image` (or the docker equivalent) should be aware of the structure underneath it. 

If I make the following change to `js_image_layer` then this works without the need for a workdir.

```diff
diff --git a/js/private/js_image_layer.bzl b/js/private/js_image_layer.bzl
index 57b059ac..e1b96fd7 100644
--- a/js/private/js_image_layer.bzl
+++ b/js/private/js_image_layer.bzl
@@ -116,6 +116,7 @@ container_image(
 # See https://github.com/aspect-build/rules_js/tree/dbb5af0d2a9a2bb50e4cf4a96dbc582b27567155#running-nodejs-programs
 # for why this is needed.
 _LAUNCHER_TMPL = """
+cd {root_dir}
 export BAZEL_BINDIR=.
 source {executable_path}
 """
@@ -123,9 +124,13 @@ source {executable_path}
 def _write_laucher(ctx, executable_path):
     "Creates a call-through shell entrypoint which sets BAZEL_BINDIR to '.' then immediately invokes the original entrypoint."
     launcher = ctx.actions.declare_file("%s_launcher.sh" % ctx.label.name)
+
+    split_by_runfiles = executable_path.split(".runfiles/")
+    root_dir = split_by_runfiles[0] + ".runfiles/" + split_by_runfiles[1].split("/")[0]
+
     ctx.actions.write(
         output = launcher,
-        content = _LAUNCHER_TMPL.format(executable_path = executable_path),
+        content = _LAUNCHER_TMPL.format(executable_path = executable_path, root_dir = root_dir),
         is_executable = True,
     )
     return launcher

```

what do you think @thesayyn?

**Comment by thesayyn** [comment] 2023-04-12 15:30
this is merely a workaround for the real problem.  under `bazel run` chdir is performed by bazel, so by the same logic `oci_image/container_image` should be the one that does the chdir. 

I see how the workaround could be a DX convenience but it might perform the wrong chdir if the layers are further processed, eg moved to a different directory. in other words; the workaround assumes that the structure of the archive will be preserved at runtime, hence the `cwd`, which might not be the case.

**Comment by LavaToaster** [comment] 2023-04-12 15:52
Sure, I get that. 

In my head I'm thinking `js_image_layer` is responsible for providing the proxy script and its runfiles directory. That proxy at minimum script should take care to ensure it's being executed within the same context as the `js_binary` would usually expect. Which is to say it should cd into `{path_to_script}.runfiles/{workspace_name}`.

If users start breaking this convention are they not essentially on their own, and then we're in this same situation? (But you've saved the majority of people who aren't interested in messing around with the how the app runs a fair amount of time?)

**Comment by thesayyn** [comment] 2023-04-12 16:12
> If users start breaking this convention are they not essentially on their own, and then we're in this same situation

you are right but we do this `cd`, we takeaway the ability to set it to something else. we can still save majority of the people auto-generating this string via a `macro` and users simply do something like this; 

```starlark
js_binary(
  name = "bin"
)

oci_image( 
  workdir = runfiles_path(":bin", root = "/app") 
)
```

**Comment by LavaToaster** [comment] 2023-04-12 16:37
If the `js_binary` has `chdir` on it then the user has no option but to `cd` into the directory for the app to be able to run it. 

Maybe an option such as `support_chdir` can be added, and/or `js_binary` adds a provider that js_image_layer can read from to influence if this is needed or not.

This problem doesn't exist if `chdir` on `js_binary` is unset.

**Comment by dmeister** [comment] 2023-04-13 20:08
I am following along because I have the same issue. The solution proposed in https://github.com/aspect-build/rules_js/issues/921#issuecomment-1486877160 appears to work at my setup. However, only once or with regular `bazel clean` calls.

However, either I am doing something wrong or it is fragile around changes due to the `no-sandbox`.
Reproduction:
1) state as in https://github.com/aspect-build/rules_js/issues/921#issuecomment-1486877160
2) `bazel clean`
3) `bazel build //apps/alpha:next_tarball`
4) Change in file `next.js/apps/alpha/pages/index.tsx`
5) `bazel build //apps/alpha:next_tarball`

Step 1-3 pass and after step 3, the image from the tarball is ready to use.

But, the command 5 is failing with
```
INFO: Analyzed target //apps/alpha:next_tarball (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/src/bazel-examples/next.js/apps/alpha/BUILD.bazel:18:5: JsRunBinary apps/alpha/.next failed: (Exit 1): next_js_binary.sh failed: error executing command (from target //apps/alpha:build) bazel-out/k8-opt-exec-2B5CBBC6-ST-e846b08c7501/bin/next_js_binary.sh build
error - ESLint must be installed in order to run during builds: npm install --save-dev eslint
warn  - Duplicate page detected. pages/_app.js and pages/_app.tsx both resolve to /_app.
warn  - Duplicate page detected. pages/api/hello.js and pages/api/hello.ts both resolve to /api/hello.
warn  - Duplicate page detected. pages/index.js and pages/index.tsx both resolve to /.

> Build error occurred
[Error: EACCES: permission denied, copyfile '/home/ubuntu/.cache/bazel/_bazel_ubuntu/105a10e78d655bdd6af3fcd43a9c1253/execroot/__main__/bazel-out/k8-fastbuild-ST-5aa765959dd8/bin/node_modules/.aspect_rules_js/next@13.0.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js' -> '/home/ubuntu/.cache/bazel/_bazel_ubuntu/105a10e78d655bdd6af3fcd43a9c1253/execroot/__main__/bazel-out/k8-fastbuild-ST-5aa765959dd8/bin/apps/alpha/node_modules/.aspect_rules_js/next@13.0.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'copyfile',
  path: '/home/ubuntu/.cache/bazel/_bazel_ubuntu/105a10e78d655bdd6af3fcd43a9c1253/execroot/__main__/bazel-out/k8-fastbuild-ST-5aa765959dd8/bin/node_modules/.aspect_rules_js/next@13.0.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js',
  dest: '/home/ubuntu/.cache/bazel/_bazel_ubuntu/105a10e78d655bdd6af3fcd43a9c1253/execroot/__main__/bazel-out/k8-fastbuild-ST-5aa765959dd8/bin/apps/alpha/node_modules/.aspect_rules_js/next@13.0.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js'
}
info  - Linting and checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
Target //apps/alpha:next_tarball failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.676s, Critical Path: 7.56s
INFO: 4 processes: 2 internal, 1 local, 1 worker.
FAILED: Build did NOT complete successfully
```

The root cause appears to be that the build action runs outside the sandbox. It has to run outside the sandbox because the files it produced in the `standalone` directory are symlinks that would only be valid inside the sandbox.

**Closed** 2023-04-19 17:02 UTC
Labels: documentation

**Comment by vohoanglong0107** [comment] 2023-04-25 01:59
I know this is a closed issue but I just want to share my approach that didn't involve the chdir workaround

**Comment by vohoanglong0107** [comment] 2023-04-25 02:06
I know this is a closed issue but I just want to share my approach that didn't involve the chdir workaround.

```
load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@aspect_bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_image_layer", "js_run_binary")
load("@rules_oci//oci:defs.bzl", "oci_image")

js_run_binary(
    name = "next",
    srcs = [
        "next.config.js",
        "package.json",
        "//:node_modules/@next/swc-linux-x64-gnu",
        "//:node_modules/next",
        "//:node_modules/react",
        "//:node_modules/react-dom",
        "//:node_modules/typescript",
        "//apps/alpha/pages",
        "//apps/alpha/public",
        "//apps/alpha/styles",
    ],
    args = ["build"],
    chdir = package_name(),
    out_dirs = [".next"],
    tool = "//:next_js_binary",
)

directory_path(
    name = "next_standalone_output",
    directory = ":next",
    path = "standalone",
)

directory_path(
    name = "next_static_output",
    directory = ":next",
    path = "static",
)

copy_to_directory(
    name = "next_standalone",
    srcs = [
        ":next_standalone_output",
        ":next_static_output",
        "//apps/alpha/public",
    ],
    out = "_next_standalone",
    replace_prefixes = {".next/standalone": "."},
)

directory_path(
    name = "next_standalone_bin",
    directory = ":next_standalone",
    path = "server.js",
)

js_binary(
    name = "site_standalone_bin",
    data = [
        "//:node_modules/next",
        "//:node_modules/react",
        "//:node_modules/react-dom",
        "//:node_modules/sharp",
    ],
    entry_point = "next_standalone_bin",
)

platform(
    name = "amd64_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

js_image_layer(
    name = "image_layers",
    binary = ":site_standalone_bin",
    platform = ":amd64_linux",
    root = "/app",
)

oci_image(
    name = "next_image",
    base = "@distroless_cc_root//:distroless_cc_root",
    cmd = ["/app/apps/alpha/site_standalone_bin"],
    entrypoint = ["bash"],
    tars = [
        "@amd64_debian11_bash//:amd64_debian11_bash",
        "@amd64_debian11_coreutils//:amd64_debian11_coreutils",
        "@amd64_debian11_debianutils//:amd64_debian11_debianutils",
        "@amd64_debian11_libtinfo6//:amd64_debian11_libtinfo6",
        ":image_layers",
    ],
)
```
