### ISSUE TITLE
Silent truncation of 64 bit integers with protobufjs package

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_js#374] opened 2022-08-09 15:08 UTC
Something about how rules_js lays out the package structure causes the protobufjs package to silently truncate 64 bit integers. The same code works as expected outside of bazel, with packages installed via `pnpm install`.

Minimal test case: https://github.com/jfirebaugh/protobufjs_bug

protobufjs does some shenanigans when loading the "long" package, so that's probably where to look:

* https://github.com/protobufjs/protobuf.js/blob/6f0806ddef408647fbaed049dbd8929ad9f5c10c/src/util/minimal.js#L180-L182
* https://github.com/protobufjs/protobuf.js/blob/6f0806ddef408647fbaed049dbd8929ad9f5c10c/lib/inquire/index.js#L10-L17

**Comment by gregmagolan** [comment] 2022-08-09 15:31
```
/**
 * Requires a module only if available.
 * @memberof util
 * @param {string} moduleName Module to require
 * @returns {?Object} Required module if available and not empty, otherwise `null`
 */
function inquire(moduleName) {
    try {
        var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
        if (mod && (mod.length || Object.keys(mod).length))
            return mod;
    } catch (e) {} // eslint-disable-line no-empty
    return null;
}
```
😱

**Comment by gregmagolan** [comment] 2022-08-09 18:19
Odd `eval("quire".replace(/^/,"re"))` aside. The reason this is working outside of bazel is that pnpm creates a
`node_modules/.pnpm/node_modules` folder and that contains `node_modules/.pnpm/node_modules/long` so that the require from `node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js` of `long` succeeds

**Comment by gregmagolan** [comment] 2022-08-09 18:20
pnpm also puts `@types` and `@protobufjs/*` in that folder

**Comment by gregmagolan** [comment] 2022-08-09 18:26
The contents of the `node_modules/.pnpm.node_modules` folder are controlled by the `hoist-pattern` which defaults to `["*"]` (https://pnpm.io/npmrc#hoist-pattern)

Setting it to,
```
hoist-pattern[]="long"
```
in an `.npmrc` is sufficient to make the minimal repro pass outside of Bazel

**Comment by gregmagolan** [comment] 2022-08-09 18:30
I'll think about how to support hoisted "phantom" dependencies in Bazel. In the meantime, this is sufficient to make this pass under Bazel,

```
$ git diff
diff --git a/BUILD.bazel b/BUILD.bazel
index bab55db..6d22306 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -8,6 +8,7 @@ js_binary(
     data = [
         "awesome.proto",
         "//:node_modules/protobufjs",
+        "//:node_modules/long",
     ],
     entry_point = "test.js",
 )
diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
index c5a9c45..8c61476 100644
--- a/WORKSPACE.bazel
+++ b/WORKSPACE.bazel
@@ -24,6 +24,9 @@ npm_translate_lock(
     name = "npm",
     pnpm_lock = "//:pnpm-lock.yaml",
     verify_node_modules_ignored = "//:.bazelignore",
+    public_hoist_packages = {
+        "long": [""]
+    }
 )
 
 load("@npm//:repositories.bzl", "npm_repositories")
```

**Comment by gregmagolan** [comment] 2022-08-09 18:34
Created https://github.com/aspect-build/rules_js/issues/375

**Comment by gregmagolan** [comment] 2022-08-10 22:28
Closing this as we know the root cause and have a work-around. Underlying issue is captured in #375.

**Closed by gregmagolan** 2022-08-10 22:28 UTC
