### ISSUE TITLE
[Bug]: `npm_translate_lock`'s `update_pnpm_lock` attribute + bzlmod errors on first build when used with external repositories (eg. `rules_ts`)

### ISSUE THREAD

**Issue by Wito-1** [aspect-build/rules_js#1371] opened 2023-11-21 22:02 UTC
### What happened?

I'm trying out `rules_js`'s `npm.translate_lock()` with `update_pnpm_lock` working with  with `rules_ts()`+ `bzlmod`

I'm finding that the first time I try to execute something like `bazel build //...` with a blank `pnpm-lock.yaml` file, the `pnpm-lock.yaml` file gets updated, but then the `BUILD.bazel` file isn't able to resolve the generated `node_modules` label.
```
BUILD.bazel:3:10: error loading package '': at /home/juan/.cache/bazel/_bazel_juan/99e149c4525c8cdc2b7c19f1841583fd/external/aspect_rules_js~override~npm~npm/defs.bzl:5:6: 
Unable to find package for @aspect_rules_js~override~npm~npm__at_ampproject_remapping__2.2.1__links//:defs.bzl: The 
repository '@aspect_rules_js~override~npm~npm__at_ampproject_remapping__2.2.1__links' could not be resolved: Repository
'@aspect_rules_js~override~npm~npm__at_ampproject_remapping__2.2.1__links' is not defined. and referenced by
'//:hello_world_ts_tsconfig'
```

On subsequent executions or if there's no need to update the pnpm-lock file, everything is able to resolve & build successfully. 

I also tested this using an e2e example in the [`rules_ts` repository](https://github.com/aspect-build/rules_ts/tree/main/e2e/bzlmod) and see the same result:
```
juan@juan-XPS-9315:~/rules_ts/e2e/bzlmod$ git diff
diff --git a/e2e/bzlmod/MODULE.bazel b/e2e/bzlmod/MODULE.bazel
index 7215263..3656ab8 100644
--- a/e2e/bzlmod/MODULE.bazel
+++ b/e2e/bzlmod/MODULE.bazel
@@ -23,6 +23,8 @@ npm = use_extension(
 npm.npm_translate_lock(
     name = "npm",
     pnpm_lock = "//:pnpm-lock.yaml",
+    update_pnpm_lock = True,
+    data = ["//:package.json"],
 )
 use_repo(npm, "npm")
```

The failing output and subsequent execution passing output (no changes in between):
```
juan@juan-XPS-9315:~/rules_ts/e2e/bzlmod$ bazel build //...
WARNING: For repository 'bazel_skylib', the root module requires module version bazel_skylib@1.4.1, but got bazel_skylib@1.4.2 in the resolved dependency graph.
ERROR: Skipping '//...': error loading package under directory '': error loading package '': at /home/juan/.cache/bazel/_bazel_juan/93cbb89bc7b7e5a7e995291e864e189e/external/aspect_rules_js~1.34.0~npm~npm/defs.bzl:7:6: Unable to find package for @aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links//:defs.bzl: The repository '@aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links' could not be resolved: Repository '@aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package under directory '': error loading package '': at /home/juan/.cache/bazel/_bazel_juan/93cbb89bc7b7e5a7e995291e864e189e/external/aspect_rules_js~1.34.0~npm~npm/defs.bzl:7:6: Unable to find package for @aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links//:defs.bzl: The repository '@aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links' could not be resolved: Repository '@aspect_rules_js~1.34.0~npm~npm__at_bufbuild_protoplugin__1.3.0__links' is not defined.
INFO: Elapsed time: 1.489s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 



juan@juan-XPS-9315:~/rules_ts/e2e/bzlmod$ bazel build //...
WARNING: For repository 'bazel_skylib', the root module requires module version bazel_skylib@1.4.1, but got bazel_skylib@1.4.2 in the resolved dependency graph.
INFO: Analyzed 7 targets (9 packages loaded, 84 targets configured).
INFO: Found 7 targets...
INFO: From Compiling src/google/protobuf/message_lite.cc [for tool]:
In file included from /usr/include/string.h:535,
                 from external/protobuf~21.7/src/google/protobuf/stubs/port.h:39,
                 from external/protobuf~21.7/src/google/protobuf/stubs/common.h:48,
                 from external/protobuf~21.7/src/google/protobuf/message_lite.h:46,
                 from external/protobuf~21.7/src/google/protobuf/message_lite.cc:36:
In function 'void* memcpy(void*, const void*, size_t)',
    inlined from 'uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)' at external/protobuf~21.7/src/google/protobuf/io/coded_stream.h:684:16,
    inlined from 'virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) const' at external/protobuf~21.7/src/google/protobuf/implicit_weak_message.h:103:28,
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at external/protobuf~21.7/src/google/protobuf/message_lite.cc:411:30:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: warning: 'void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: Elapsed time: 34.200s, Critical Path: 18.61s
INFO: 131 processes: 1 internal, 130 linux-sandbox.
INFO: Build completed successfully, 131 total actions
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
```
bazel_dep(name = "aspect_bazel_lib", version = "1.38.1")
bazel_dep(name = "aspect_rules_js", version = "1.34.0")
bazel_dep(name = "aspect_rules_ts", version = "2.1.0")
```

Language(s) and/or frameworks involved:
TS

### How to reproduce

```shell
This can be reproduced by:
1. Cloning the rules_ts repo and navigating to the e2e/bzlmod dir:

git clone https://github.com/aspect-build/rules_ts.git && cd rules_ts/e2e/bzlmod
```

2. make the following modifications to the [`rules_ts` repository](https://github.com/aspect-build/rules_ts/tree/main/e2e/bzlmod):
```
juan@juan-XPS-9315:~/rules_ts/e2e/bzlmod$ git diff
diff --git a/e2e/bzlmod/MODULE.bazel b/e2e/bzlmod/MODULE.bazel
index 7215263..3656ab8 100644
--- a/e2e/bzlmod/MODULE.bazel
+++ b/e2e/bzlmod/MODULE.bazel
@@ -23,6 +23,8 @@ npm = use_extension(
 npm.npm_translate_lock(
     name = "npm",
     pnpm_lock = "//:pnpm-lock.yaml",
+    update_pnpm_lock = True,
+    data = ["//:package.json"],
 )
 use_repo(npm, "npm")
```
3. clear the contents of the `pnpm-lock.yaml` file: 
```
echo "" > pnpm-lock.yaml
```
4. build 
```
bazel build //...
```
```


### Any other information?

_No response_

**Comment by gregmagolan** [comment] 2024-01-22 19:31
@jbedard I think your recent change resolved this issue?

**Comment by jbedard** [comment] 2024-01-22 20:03
https://github.com/aspect-build/rules_js/commit/83ceefd5fe942c13af7da56e03915ce99a748929 adds a warning explaining the issue but I don't think we can actually fix this.

I think https://github.com/aspect-build/rules_js/issues/1445 is actually a dupe of this issue but I'm going to close this one since the https://github.com/aspect-build/rules_js/issues/1445 URL is in the error message presented to the user.

**Closed by jbedard** 2024-01-22 20:03 UTC
Labels: bug
